name: Benchmark

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'v**'
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'v**'

jobs:
  benchmark:
    name: perf regressions
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install wabt
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.x'
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: make build

    # Run benchmark with `go test -bench` and stores the output to a file
    - name: Run benchmark
      run: make benchmark | tee benchmark_results.txt

    # Download previous benchmark result from cache (if exists)
    - name: Download previous benchmark data
      uses: actions/cache@v1
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    # Run `github-action-benchmark` action
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        # What benchmark tool the benchmark_results.txt came from
        tool: 'go'

        # Where the output from the benchmark tool is stored
        output-file-path: benchmark_results.txt

        # Where the previous data file is stored
        external-data-json-path: ./cache/benchmark-data.json
        comment-always: true
        alert-threshold: '120%'
        github-token: ${{ secrets.GITHUB_TOKEN }}

        # Enable below to create a PR comment with a warning,
        # if performance degrades more than the given threshold.
        # comment-on-alert: true

        # Enable below to fail the PR if performance degrades more than the given threshold.
        # fail-on-alert: true
