name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Base branch'
        required: false
        default: 'master'


jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      base-branch: ${{ inputs.base }}
      chain: flow-mainnet
      url: access.mainnet.nodes.onflow.org:9000
