name: BackwardCompatibilityCheck

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Current branch/tag'
        required: true
        default: 'master'
      base:
        description: 'Base branch/tag'
        required: true
        default: 'latest'
  pull_request:
    branches:
      - master
      - 'v**'

env:
  GO_VERSION: '1.19.2'

concurrency:
  group: ${{ github.workflow }}-${{ inputs.base || github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      # Set step output to a job output, so that next job can read this value.
      branch: ${{ steps.setup.outputs.branch }}
      base: ${{ steps.setup.outputs.base }}
    steps:
      - name: Setup
        id: setup
        if: github.event_name == 'pull_request'
        run: |
          # If the workflow is running on a pull request, then take the PR's source branch as the current branch,
          # and the PR's target as the base branch.
          if [[ "${{ github.${{ github.event.pull_request.head.sha }} }}" == "pull_request" ]]; then
            echo "branch=v`(echo "${{ github.event.pull_request.head.sha }}")`" >> $GITHUB_OUTPUT
            echo "base=v`(echo "${{ github.base_ref }}")`" >> $GITHUB_OUTPUT
          else
            echo "branch=v`(echo "${{ inputs.branch }}")`" >> $GITHUB_OUTPUT
            echo "base=v`(echo "${{ inputs.base }}")`" >> $GITHUB_OUTPUT
          fi

  mainnet:
    uses: ./.github/workflows/compatibility-check-template.yml
    with:
      base-branch: ${{ needs.setup.outputs.base }}
      current-branch: ${{ needs.setup.outputs.branch }}
      chain: flow-mainnet
      url: access.mainnet.nodes.onflow.org:9000

  testnet:
    uses: ./.github/workflows/compatibility-check-template.yml
    with:
      base-branch:  ${{ needs.setup.outputs.base }}
      current-branch: ${{ needs.setup.outputs.branch }}
      chain: flow-testnet
      url: access.testnet.nodes.onflow.org:9000
