name: BackwardCompatibilityCheckTemplate

on:
  workflow_call:
    inputs:
      base-branch:
        required: true
        type: string
      chain:
        required: true
        type: string
      url:
        required: true
        type: string

env:
  GO_VERSION: '1.19.2'

concurrency:
  group: ${{ github.workflow }}-${{ inputs.base-branch || github.run_id }}-${{ inputs.chain }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Make output dirs
        run: |
          mkdir tmp
          
      - name: Generate chache key
        id: cache-key-generator
        run: echo "cache-key=${{ github.workflow }}-${{ inputs.chain }}-${{ inputs.base-branch }}-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # Get contracts
      
      - name: Restore Cached Contracts
        id: restore-cached-contracts
        uses: actions/cache/restore@v3
        with:
          path: tmp/contracts.csv
          key: ${{ steps.cache-key-generator.outputs.cache-key }}-contracts

      - name: Download contracts
        if: ${{ steps.restore-cached-contracts.outputs.cache-hit != 'true' }}
        working-directory: ./tools/batch-script
        run: |
          go run ./cmd/get_contracts/main.go --chain=${{ inputs.chain }} --u=${{ inputs.url }} > ../../tmp/contracts.csv
          
      - name: Cach Contracts
        id: cach-contracts
        if: ${{ steps.restore-cached-contracts.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v3
        with:
          path: tmp/contracts.csv
          key: ${{ steps.cache-key-generator.outputs.cache-key }}-contracts

      # Check contracts using current branch
      
      - name: Restor cached new checking results
        id: restore-cached-new-results
        uses: actions/cache/restore@v3
        with:
          path: tmp/output-new.txt
          key: ${{ steps.cache-key-generator.outputs.cache-key }}-new-results

      - name: Check contracts using current branch
        if: ${{ steps.restore-cached-new-results.outputs.cache-hit != 'true' }}
        working-directory: ./tools/compatibility-check
        run: |
          go run ./cmd/check_contracts/main.go ../../tmp/contracts.csv ../../tmp/output-new.txt
     
      - name: Cach new checking results
        id: cach-new-results
        if: ${{ steps.restore-cached-new-results.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v3
        with:
          path: tmp/output-new.txt
          key: ${{ steps.cache-key-generator.outputs.cache-key }}-new-results
          
      # Check contracts using base branch
       
      - name: Checkout base branch
        run: git checkout ${{ inputs.base-branch }}

      - name: Restore cached old checking results
        id: restore-cached-old-results
        uses: actions/cache@v3
        with:
          path: tmp/output-old.txt
          key: ${{ steps.cache-key-generator.outputs.cache-key }}-old-results

      - name: Check contracts using base branch
        if: ${{ steps.restore-cached-old-results.outputs.cache-hit != 'true' }}
        working-directory: ./tools/compatibility-check
        run: |
          go run ./cmd/check_contracts/main.go ../../tmp/contracts.csv ../../tmp/output-old.txt

      - name: Cach old checking results
        id: cach-old-results
        if: ${{ steps.restore-cached-old-results.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v3
        with:
          path: tmp/output-old.txt
          key: ${{ steps.cache-key-generator.outputs.cache-key }}-old-results

      # Check Diff
      - name: Check diff
        run: |
          go run ./cmd/check_diff/main.go ../../tmp/output-old.txt ../../tmp/output-new.txt
