name: BackwardCompatibilityCheck

on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Base branch'
        required: false
        default: 'master'

env:
  GO_VERSION: '1.19.2'

concurrency:
  group: ${{ github.job }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  mainnet:
    uses: supuns/cadence/.github/workflows/compatibility-check-template.yml@master
    with:
      base-branch: ${{ github.event.pull_request.base.sha }}
      chain: flow-mainnet
      url: access.mainnet.nodes.onflow.org:9000

  testnet:
    uses: supuns/cadence/.github/workflows/compatibility-check-template.yml@master
    with:
      base-branch:  ${{ inputs.base }}
      chain: flow-testnet
      url: access.testnet.nodes.onflow.org:9000
