# This workflow automates the release process.
# It follows the below steps:
#   - Bump the version to the target release version
#   - Run tests and lint
#   - Create and push a branch `release/v<version>` with version bump changes
#   - Open a PR from `release/<version>` branch to `master`
#   - Create and push a release tag with name `v<version>`

name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      base:
        description: 'Base branch for the release'
        required: true
        default: 'master'

env:
  GO_VERSION: '1.19.2'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:

  # Bump the version, run the tests_lint, and push the changes to a release branch.
  version-bump:
    name: "${{ github.event.inputs.version }}"
    runs-on: ubuntu-latest
    outputs:
      # Set step output to a job output, so that next job can read this value.
      version: ${{ steps.version-gen.outputs.version }}
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install wabt

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.base }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      # Unify the version to the format `v0.1.0`.
      # This is to support both version formats: `0.1.0` and `v0.1.0`.
      - name: Cleanup version
        id: version-gen
        run: echo "version=v`(echo "${{ github.event.inputs.version }}" | sed -Ee 's/^v//')`" >> $GITHUB_OUTPUT

      - name: Bump Version
        run: make release bump=${{ steps.version-gen.outputs.version }}

      - name: Run Tests
        run: |
          make test
          make lint-github-actions

      - name: Config git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release/${{ steps.version-gen.outputs.version }}
          title: 'Merge `release/${{ steps.version-gen.outputs.version }}` to `${{ inputs.base }}`'
          commit-message: ${{ steps.version-gen.outputs.version }}
          body: |
            Merge `release/${{ steps.version-gen.outputs.version }}` branch to `${{ inputs.base }}`

  # Create a tag from the release branch created in previous job.
  # Requires approval.
  release:
    needs: version-bump
    name: "${{ github.event.inputs.version }}"
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{needs.version-bump.outputs.version}}

      - name: Tag and Push
        run: |
          git checkout release/${{needs.version-bump.outputs.version}}
          git tag ${{needs.version-bump.outputs.version}}
          git push origin ${{needs.version-bump.outputs.version}}
