name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      base:
        description: 'Base branch for the release'
        required: false
        default: 'master'

env:
  GO_VERSION: '1.19.2'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install wabt

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Create release branch
        run: |
          git checkout ${{ github.event.inputs.base }}
          git checkout -b release/v${{ github.event.inputs.version }}
          git push origin release/v${{ github.event.inputs.version }}

      - name: Version bump
        run: make release bump=${{ github.event.inputs.version }}

      - name: Commit
        run: git commit -m "${{ github.event.inputs.version }}"

      - name: Tag and Push
        run: |
          git push

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release/v${{ github.event.inputs.version }}
          title: 'Merge `release/${{ github.event.inputs.version }}` to `master`'
          body: |
            Merge `release/$v{{ github.event.inputs.version }}` branch to `master`
