name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      base:
        description: 'Base branch for the release'
        required: false
        default: 'master'

env:
  GO_VERSION: '1.19.2'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create release branch
        run: |
          git checkout ${{ github.event.inputs.base }}
          git checkout -b release/${{ github.event.inputs.version }}
          git push origin release/${{ github.event.inputs.version }}

