name: Reusable workflow example

on:
  workflow_call:
    inputs:
      base-branch:
        required: true
        type: string
      chain:
        required: true
        type: string
      url:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Print something
      run: echo "************ Hello!!"
