# Open a PR in onflow/flow when a documentation PR got merged

name: Sync onflow/flow docs

on:
  pull_request:
    branches:
      - master
    types: [closed]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  sync-flow-docs:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout onflow/flow
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.REMOTE_REPO_PAT }}
          repository: onflow/flow

      - name: Create commit
        run: |
          git config --global user.email "bot@onflow.org"
          git config --global user.name "Flow Bot"
          git commit --allow-empty -m "update Cadence docs"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REMOTE_REPO_PAT }}
          commit-message: Update Cadence docs
          title: "Auto Cadence Update"
          body: |
              Auto generated PR to update Cadence docs.

              References: ${{ github.event.pull_request.html_url }}

              **MERGE this PR**! Rebasing will not work!

          branch: auto-cadence-upgrade/${{ github.run_id }}_${{ github.run_number }}
          delete-branch: true
          assignees: turbolent
